spring:
  application:
    name: orders
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
  main:
    allow-bean-definition-overriding: true
server:
  port: 8100
order:
  rabbitmq:
    exchange: servicesExchange
    routingKey: orders.*
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true