spring:
  application:
    name: warehouse
  rabbitmq:
    port: 5672
    host: localhost
server:
  port: 8200
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true